# [Choice] Node.js version (use -bookworm variants only)
ARG VARIANT=22-bookworm
FROM mcr.microsoft.com/devcontainers/javascript-node:${VARIANT}

# [Optional] Install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list>

# [Optional] Uncomment if you want to install more global node packages.
# RUN npm install -g <your-package-list>